version: '3'
networks: 
  postgres-network:
    driver: bridge

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    networks:
    - postgres-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
  # nestjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    networks:
      - postgres-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
  db-test:
    image: postgres
    networks:
      - postgres-network
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-test:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  db-data:
  pgadmin-data:
  db-test:
